servicioRest/config/routes.rb
Rails.application.routes.draw do
  resources :tipopersonas
  resources :personas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

servicioRest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

servicioRest/app/models/persona.rb
class Persona < ApplicationRecord
end

servicioRest/app/models/tipopersona.rb
class Tipopersona < ApplicationRecord
end

servicioRest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

servicioRest/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona fue borrada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :edad)
    end
end

servicioRest/app/controllers/tipopersonas_controller.rb
class TipopersonasController < ApplicationController
  before_action :set_tipopersona, only: [:show, :edit, :update, :destroy]

  # GET /tipopersonas
  # GET /tipopersonas.json
  def index
    @tipopersonas = Tipopersona.all
  end

  # GET /tipopersonas/1
  # GET /tipopersonas/1.json
  def show
  end

  # GET /tipopersonas/new
  def new
    @tipopersona = Tipopersona.new
  end

  # GET /tipopersonas/1/edit
  def edit
  end

  # POST /tipopersonas
  # POST /tipopersonas.json
  def create
    @tipopersona = Tipopersona.new(tipopersona_params)

    respond_to do |format|
      if @tipopersona.save
        format.html { redirect_to @tipopersona, notice: 'Tipopersona was successfully created.' }
        format.json { render :show, status: :created, location: @tipopersona }
      else
        format.html { render :new }
        format.json { render json: @tipopersona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipopersonas/1
  # PATCH/PUT /tipopersonas/1.json
  def update
    respond_to do |format|
      if @tipopersona.update(tipopersona_params)
        format.html { redirect_to @tipopersona, notice: 'Tipopersona was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipopersona }
      else
        format.html { render :edit }
        format.json { render json: @tipopersona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipopersonas/1
  # DELETE /tipopersonas/1.json
  def destroy
    @tipopersona.destroy
    respond_to do |format|
      format.html { redirect_to tipopersonas_url, notice: 'Tipopersona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipopersona
      @tipopersona = Tipopersona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipopersona_params
      params.require(:tipopersona).permit(:nombretipo)
    end
end

servicioRest/app/helpers/application_helper.rb
module ApplicationHelper
end

servicioRest/app/helpers/personas_helper.rb
module PersonasHelper
end

servicioRest/app/helpers/tipopersonas_helper.rb
module TipopersonasHelper
end

servicioRest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServicioRest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

servicioRest/app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :persona_nombre %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad, id: :persona_edad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

servicioRest/app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

servicioRest/app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.edad %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

servicioRest/app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

servicioRest/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.edad %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>

servicioRest/app/views/tipopersonas/_form.html.erb
<%= form_with(model: tipopersona, local: true) do |form| %>
  <% if tipopersona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipopersona.errors.count, "error") %> prohibited this tipopersona from being saved:</h2>

      <ul>
      <% tipopersona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombretipo %>
    <%= form.text_field :nombretipo, id: :tipopersona_nombretipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

servicioRest/app/views/tipopersonas/edit.html.erb
<h1>Editing Tipopersona</h1>

<%= render 'form', tipopersona: @tipopersona %>

<%= link_to 'Show', @tipopersona %> |
<%= link_to 'Back', tipopersonas_path %>

servicioRest/app/views/tipopersonas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipopersonas</h1>

<table>
  <thead>
    <tr>
      <th>Nombretipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipopersonas.each do |tipopersona| %>
      <tr>
        <td><%= tipopersona.nombretipo %></td>
        <td><%= link_to 'Show', tipopersona %></td>
        <td><%= link_to 'Edit', edit_tipopersona_path(tipopersona) %></td>
        <td><%= link_to 'Destroy', tipopersona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipopersona', new_tipopersona_path %>

servicioRest/app/views/tipopersonas/new.html.erb
<h1>New Tipopersona</h1>

<%= render 'form', tipopersona: @tipopersona %>

<%= link_to 'Back', tipopersonas_path %>

servicioRest/app/views/tipopersonas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombretipo:</strong>
  <%= @tipopersona.nombretipo %>
</p>

<%= link_to 'Edit', edit_tipopersona_path(@tipopersona) %> |
<%= link_to 'Back', tipopersonas_path %>